import { Router } from 'express';

import { defineRoutes } from '../../../utils/defineRoute';
import {
  forgotPasswordRateLimit,
  loginRateLimit,
  mfaRateLimit,
  refreshRateLimit,
  registerRateLimit,
  resetPasswordRateLimit,
} from '../../../middleware/rateLimit';

import {
  changePasswordController,
  forgotPasswordController,
  loginController,
  logoutAllController,
  logoutController,
  meController,
  mfaConfirmEmailSetupController,
  mfaConfirmSetupController,
  mfaDisableController,
  mfaResendController,
  mfaSetupController,
  mfaSetupEmailController,
  mfaVerifyLoginController,
  refreshController,
  registerController,
  resetPasswordController,
  validateResetTokenController,
} from '../controller';
import {
  changePasswordSchema,
  forgotPasswordSchema,
  loginSchema,
  logoutSchema,
  mfaDisableSchema,
  mfaResendSchema,
  mfaVerifyLoginSchema,
  mfaVerifySetupSchema,
  refreshSchema,
  registerSchema,
  resetPasswordSchema,
  validateResetTokenQuerySchema,
} from '../validator';

const router = Router();

defineRoutes(router, [
  {
    method: 'post',
    path: '/login',
    auth: 'public',
    preAuth: [loginRateLimit],
    schema: { body: loginSchema },
    handler: loginController,
  },
  {
    method: 'post',
    path: '/mfa/verify',
    auth: 'public',
    preAuth: [mfaRateLimit],
    schema: { body: mfaVerifyLoginSchema },
    handler: mfaVerifyLoginController,
  },
  {
    method: 'post',
    path: '/register',
    auth: 'public',
    preAuth: [registerRateLimit],
    schema: { body: registerSchema },
    handler: registerController,
  },
  {
    method: 'post',
    path: '/refresh',
    auth: 'public',
    preAuth: [refreshRateLimit],
    schema: { body: refreshSchema },
    handler: refreshController,
  },
  {
    method: 'get',
    path: '/me',
    auth: 'authenticated',
    schema: {},
    handler: meController,
  },
  {
    method: 'post',
    path: '/logout',
    auth: 'authenticated',
    schema: { body: logoutSchema },
    handler: logoutController,
  },
  {
    method: 'post',
    path: '/logout-all',
    auth: 'authenticated',
    schema: {},
    handler: logoutAllController,
  },
  {
    method: 'post',
    path: '/change-password',
    auth: 'authenticated',
    schema: { body: changePasswordSchema },
    handler: changePasswordController,
  },
  {
    method: 'post',
    path: '/mfa/setup',
    auth: 'authenticated',
    schema: {},
    handler: mfaSetupController,
  },
  {
    method: 'post',
    path: '/mfa/setup/confirm',
    auth: 'authenticated',
    preAuth: [mfaRateLimit],
    schema: { body: mfaVerifySetupSchema },
    handler: mfaConfirmSetupController,
  },
  {
    method: 'post',
    path: '/mfa/setup/email',
    auth: 'authenticated',
    preAuth: [mfaRateLimit],
    schema: {},
    handler: mfaSetupEmailController,
  },
  {
    method: 'post',
    path: '/mfa/setup/email/confirm',
    auth: 'authenticated',
    preAuth: [mfaRateLimit],
    schema: { body: mfaVerifySetupSchema },
    handler: mfaConfirmEmailSetupController,
  },
  {
    method: 'post',
    path: '/mfa/resend',
    auth: 'public',
    preAuth: [mfaRateLimit],
    schema: { body: mfaResendSchema },
    handler: mfaResendController,
  },
  {
    method: 'post',
    path: '/mfa/disable',
    auth: 'authenticated',
    schema: { body: mfaDisableSchema },
    handler: mfaDisableController,
  },
  {
    method: 'post',
    path: '/forgot-password',
    auth: 'public',
    preAuth: [forgotPasswordRateLimit],
    schema: { body: forgotPasswordSchema },
    handler: forgotPasswordController,
  },
  {
    method: 'get',
    path: '/reset-password/validate',
    auth: 'public',
    preAuth: [resetPasswordRateLimit],
    schema: { query: validateResetTokenQuerySchema },
    handler: validateResetTokenController,
  },
  {
    method: 'post',
    path: '/reset-password',
    auth: 'public',
    preAuth: [resetPasswordRateLimit],
    schema: { body: resetPasswordSchema },
    handler: resetPasswordController,
  },
]);

export default router;
