import type { ThemeTokens } from "./design-tokens";

/**
 * Complete default token set — mirrors the @default values in the Prisma Theme
 * model. Used as a safe fallback when no theme is found and as the initial
 * state for the admin Theme Builder.
 */
export const DEFAULT_THEME_TOKENS: ThemeTokens = {
  // COLOR — Beige Luxury palette: warm sand, champagne, soft bronze accents
  colorPrimary: "#2F241D",
  colorPrimaryHover: "#A67C52",
  colorPrimaryActive: "#6D5C50",
  colorPrimaryForeground: "#FFFDF9",
  colorSecondary: "#2F241D",
  colorSecondaryHover: "#A67C52",
  colorSecondaryForeground: "#F8F4EE",
  colorAccent: "#B08968",
  colorAccentHover: "#A67C52",
  colorAccentForeground: "#FFFDF9",
  colorBackground: "#F8F4EE",
  colorSurface: "#FFFDF9",
  colorSurfaceElevated: "#F1E9DD",
  colorBorder: "#E5D8C7",
  colorBorderFocus: "#B08968",
  colorText: "#2F241D",
  colorTextMuted: "#6D5C50",
  colorTextInverse: "#FFFDF9",
  colorSuccess: "#5B8A5A",
  colorSuccessForeground: "#FFFDF9",
  colorWarning: "#C08A3E",
  colorWarningForeground: "#FFFDF9",
  colorError: "#A8584F",
  colorErrorForeground: "#FFFDF9",
  colorInfo: "#7C6F63",
  colorInfoForeground: "#FFFDF9",
  colorOverlay: "rgba(47,36,29,0.5)",
  colorSkeleton: "#F1E9DD",

  // TYPOGRAPHY
  // Use local Handel font as the primary site font for display, body and UI.
  // Keep mono as JetBrains Mono for code blocks.
  fontFamilyDisplay: "Handel",
  fontFamilyBody: "Handel",
  fontFamilyMono: "JetBrains Mono",
  fontFamilyUI: "Handel",
  fontWeightLight: 300,
  fontWeightRegular: 400,
  fontWeightMedium: 500,
  fontWeightSemibold: 600,
  fontWeightBold: 700,
  fontWeightBlack: 900,
  fontSizeXs: "0.75rem",
  fontSizeSm: "0.875rem",
  fontSizeBase: "1rem",
  fontSizeLg: "1.125rem",
  fontSizeXl: "1.25rem",
  fontSize2xl: "1.5rem",
  fontSize3xl: "1.875rem",
  fontSize4xl: "2.25rem",
  fontSize5xl: "3rem",
  lineHeightTight: 1.1,
  lineHeightNormal: 1.5,
  lineHeightRelaxed: 1.75,
  letterSpacingTight: "-0.02em",
  letterSpacingNormal: "0em",
  letterSpacingWide: "0.05em",

  // SPACING & LAYOUT
  spacingUnit: "4px",
  containerMaxWidth: "1280px",
  containerPaddingX: "1.5rem",
  sectionPaddingY: "4rem",
  gridGap: "1.5rem",
  gridColumns: 4,
  gridColumnsMobile: 2,

  // BORDER & SHAPE
  borderRadiusNone: "0px",
  borderRadiusSm: "4px",
  borderRadiusMd: "8px",
  borderRadiusLg: "12px",
  borderRadiusXl: "16px",
  borderRadius2xl: "24px",
  borderRadiusFull: "9999px",
  borderRadiusCard: "24px",
  borderRadiusButton: "9999px",
  borderRadiusInput: "14px",
  borderRadiusBadge: "9999px",
  borderRadiusImage: "20px",
  borderWidth: "1px",
  borderStyle: "solid",
  borderColor: "#E5D8C7",

  // SHADOW
  shadowNone: "none",
  shadowXs: "0 1px 2px rgba(47,36,29,0.04)",
  shadowSm: "0 2px 10px rgba(47,36,29,0.06)",
  shadowMd: "0 8px 24px rgba(47,36,29,0.08)",
  shadowLg: "0 16px 40px rgba(47,36,29,0.10)",
  shadowXl: "0 28px 60px rgba(47,36,29,0.12)",
  shadowInner: "inset 0 2px 4px rgba(47,36,29,0.05)",
  shadowGlow: "0 0 24px rgba(176,137,104,0.4)",
  shadowCard: "sm",
  shadowCardHover: "lg",
  shadowButton: "xs",
  shadowModal: "xl",
  shadowDropdown: "lg",
  shadowColor: "#2F241D",

  // BUTTON
  buttonShape: "rounded",
  buttonVariantPrimary: "solid",
  buttonVariantSecondary: "outline",
  buttonHoverEffect: "lift",
  buttonTransitionMs: 200,
  buttonPaddingX: "1.25rem",
  buttonPaddingY: "0.625rem",
  buttonFontWeight: 600,
  buttonLetterSpacing: "0em",
  buttonTextTransform: "none",
  buttonIconPosition: "left",
  buttonLoadingStyle: "spinner",

  // CARD
  cardStyle: "outlined",
  cardHoverEffect: "lift",
  cardHoverTransitionMs: 200,
  cardImageRatio: "1:1",
  cardImageFit: "cover",
  cardImagePosition: "center",
  cardPaddingX: "1rem",
  cardPaddingY: "1rem",
  cardShowQuickBuy: true,
  cardShowWishlist: true,
  cardShowCompare: false,
  cardShowRating: true,
  cardShowBadges: true,
  cardBadgeStyle: "pill",

  // PATTERN
  patternType: "solid",
  patternColorA: "#F8F4EE",
  patternColorB: "#F1E9DD",
  patternColorC: "#B08968",
  patternOpacity: 1.0,
  patternSize: "24px",
  patternAngle: 45,
  patternBlur: "0px",
  patternSaturation: 100,
  overlayType: "none",
  overlayColor: "rgba(0,0,0,0.3)",
  overlayOpacity: 0.3,
  overlayBlendMode: "normal",

  // ANIMATION
  animationEnabled: true,
  animationReducedMotion: true,
  animationEntrance: "fadeIn",
  animationEntranceDuration: 500,
  animationEntranceDelay: 0,
  animationEasing: "easeOut",
  animationStagger: 80,
  animationScrollTrigger: true,
  animationHoverScale: 1.03,
  animationHoverDuration: 200,
  animationPageTransition: "fade",
  animationLoadingStyle: "skeleton",

  // HEADER & NAV
  headerStyle: "solid",
  headerHeight: "72px",
  headerSticky: true,
  headerScrollBehavior: "always-visible",
  navStyle: "horizontal",
  navItemSpacing: "1.5rem",
  navActiveIndicator: "underline",
  mobileMenuStyle: "drawer-left",
  cartIconStyle: "bag",
};
